import type {
  AnalyticsKPI,
  PlatformBreakdown,
  CreativePerformanceView,
  AnalyticsAIInsight,
  CampaignAnalytics,
  CampaignStatus,
  AnalyticsOverview,
  ReachTrendDataPoint,
  CampaignMetrics,
  CreativeMetrics,
  AIInsight,
  ReportTemplate,
  GeneratedReport,
  ScheduledReport,
} from '@repo/types'

export const mockAnalyticsKPIs: AnalyticsKPI[] = [
  { label: 'Total Reach', value: '12.4K', change: 23, trend: 'up' },
  { label: 'Engagement', value: '856', change: 12, trend: 'up' },
  { label: 'CTR', value: '3.2%', change: -0.4, trend: 'down' },
  { label: 'Clicks', value: '245', change: 8, trend: 'up' },
  { label: 'Saves', value: '42', change: 31, trend: 'up' },
]

export const mockPlatformBreakdown: PlatformBreakdown[] = [
  {
    platform: 'Instagram',
    reach: 8432,
    engagement: 582,
    clicks: 167,
    percentage: 68,
    color: 'oklch(0.66 0.21 354)',
  },
  {
    platform: 'Facebook',
    reach: 2604,
    engagement: 178,
    clicks: 51,
    percentage: 21,
    color: 'oklch(0.55 0.18 250)',
  },
  {
    platform: 'TikTok',
    reach: 1364,
    engagement: 96,
    clicks: 27,
    percentage: 11,
    color: 'oklch(0.75 0.15 180)',
  },
]

export const mockTopCreatives: CreativePerformanceView[] = [
  {
    id: 'creative-1', name: 'Honor Her Story', campaignName: "Mother's Day Collection",
    platform: 'Instagram', format: 'Story', thumbnailUrl: 'https://placehold.co/200x350/1c1b1b/c5a55a?text=HHS',
    reach: 4200, impressions: 5800, engagementRate: 6.8, ctr: 5.1, clicks: 296, saves: 18,
    performanceScore: 92, performanceLabel: 'excellent', publishedAt: new Date('2026-02-25T10:00:00Z'),
  },
  {
    id: 'creative-2', name: 'Spring Awakening', campaignName: 'Spring 2026',
    platform: 'Instagram', format: 'Feed', thumbnailUrl: 'https://placehold.co/200x200/2d4a3e/a8d5ba?text=SA',
    reach: 3100, impressions: 4200, engagementRate: 5.2, ctr: 4.3, clicks: 181, saves: 12,
    performanceScore: 85, performanceLabel: 'excellent', publishedAt: new Date('2026-02-24T14:00:00Z'),
  },
  {
    id: 'creative-3', name: 'Timeless Heritage', campaignName: 'Brand Awareness Q1',
    platform: 'Facebook', format: 'Feed', thumbnailUrl: 'https://placehold.co/200x200/e6d3c1/1c1b1b?text=TH',
    reach: 2800, impressions: 3900, engagementRate: 3.9, ctr: 3.1, clicks: 121, saves: 8,
    performanceScore: 72, performanceLabel: 'good', publishedAt: new Date('2026-02-23T09:00:00Z'),
  },
  {
    id: 'creative-4', name: 'Fitness Friday', campaignName: 'Weekly Engagement',
    platform: 'TikTok', format: 'Video', thumbnailUrl: 'https://placehold.co/200x350/000000/00ff00?text=FF',
    reach: 1800, impressions: 2400, engagementRate: 4.5, ctr: 2.8, clicks: 67, saves: 3,
    performanceScore: 68, performanceLabel: 'good', publishedAt: new Date('2026-02-26T16:00:00Z'),
  },
  {
    id: 'creative-5', name: 'Ancient Craft', campaignName: 'Brand Awareness Q1',
    platform: 'Instagram', format: 'Story', thumbnailUrl: 'https://placehold.co/200x350/8b7355/ffffff?text=AC',
    reach: 500, impressions: 1600, engagementRate: 0.8, ctr: 0.3, clicks: 5, saves: 0,
    performanceScore: 18, performanceLabel: 'critical', publishedAt: new Date('2026-02-22T11:00:00Z'),
  },
]

export const mockTimeSeriesData = Array.from({ length: 30 }, (_, i) => {
  const date = new Date('2026-02-01')
  date.setDate(date.getDate() + i)
  const base = 300 + Math.sin(i / 4) * 150
  return {
    date: date.toISOString().split('T')[0],
    reach: Math.round(base + ((i * 137 + 43) % 200)),
    engagement: Math.round((base + ((i * 89 + 67) % 200)) * 0.07),
  }
})

export const mockCampaignAnalytics: CampaignAnalytics[] = [
  {
    id: 'campaign-1', name: "Mother's Day Collection", brandName: 'Golden Horn Jewellery',
    status: 'PUBLISHED' as CampaignStatus, platforms: ['Instagram', 'Facebook'], creativeCount: 8,
    totalReach: 8200, totalEngagement: 558, avgCtr: 4.7, avgEngagementRate: 6.8,
    spend: 120, roas: 4.2, startDate: new Date('2026-02-20'), endDate: null,
  },
  {
    id: 'campaign-2', name: 'Spring 2026', brandName: 'Golden Horn Jewellery',
    status: 'PUBLISHED' as CampaignStatus, platforms: ['Instagram'], creativeCount: 5,
    totalReach: 5400, totalEngagement: 281, avgCtr: 3.8, avgEngagementRate: 5.2,
    spend: 80, roas: 3.5, startDate: new Date('2026-02-18'), endDate: null,
  },
  {
    id: 'campaign-3', name: 'Brand Awareness Q1', brandName: 'Golden Horn Jewellery',
    status: 'PUBLISHED' as CampaignStatus, platforms: ['Instagram', 'Facebook', 'TikTok'], creativeCount: 12,
    totalReach: 4600, totalEngagement: 179, avgCtr: 1.7, avgEngagementRate: 2.4,
    spend: 200, roas: 1.8, startDate: new Date('2026-02-10'), endDate: null,
  },
  {
    id: 'campaign-4', name: 'Weekly Engagement', brandName: 'Urban Fitness Co',
    status: 'PUBLISHED' as CampaignStatus, platforms: ['TikTok', 'Instagram'], creativeCount: 6,
    totalReach: 3200, totalEngagement: 144, avgCtr: 2.8, avgEngagementRate: 4.5,
    spend: 60, roas: 2.9, startDate: new Date('2026-02-15'), endDate: null,
  },
  {
    id: 'campaign-5', name: 'New Year Promo', brandName: 'Golden Horn Jewellery',
    status: 'COMPLETED' as CampaignStatus, platforms: ['Instagram', 'Facebook'], creativeCount: 10,
    totalReach: 15800, totalEngagement: 1106, avgCtr: 5.2, avgEngagementRate: 7.0,
    spend: 350, roas: 6.1, startDate: new Date('2025-12-20'), endDate: new Date('2026-01-05'),
  },
]

export const mockAIInsightsLegacy: AnalyticsAIInsight[] = [
  { id: 'insight-1', type: 'success', title: 'Story format outperforms Feed', description: 'Your Instagram Stories have 2.3x higher CTR than Feed posts. Consider allocating more creatives to Stories.', metric: 'CTR +130%' },
  { id: 'insight-2', type: 'warning', title: '"Ancient Craft" underperforming', description: 'This creative has 0.3% CTR after 5 days. Autopilot has paused it. Consider replacing with a new variant.', metric: 'CTR 0.3%', creativeId: 'creative-5' },
  { id: 'insight-3', type: 'suggestion', title: 'Best posting time: 10:00-11:00', description: 'Your audience is most active between 10-11 AM. Schedule high-priority content in this window.', metric: '+45% engagement' },
  { id: 'insight-4', type: 'trend', title: 'Engagement trending up', description: 'Overall engagement has increased 12% this week compared to last week. Keep the momentum going!', metric: '+12% weekly' },
  { id: 'insight-5', type: 'suggestion', title: 'Add TikTok to your mix', description: 'Your TikTok content reaches a younger demographic with 4.5% engagement rate. Scale up TikTok creatives.', metric: '4.5% engagement' },
]

// Analytics Overview (Last 30 days)
export const mockAnalyticsOverview: AnalyticsOverview = {
  totalReach: 12400,
  totalReachChange: 23,
  totalEngagement: 856,
  totalEngagementChange: 12,
  avgCtr: 3.2,
  avgCtrChange: -0.4,
  totalClicks: 245,
  totalClicksChange: 8,
  totalSaves: 187,
  totalSavesChange: 31,
}

// Reach Trend (Last 30 days) — deterministic
export const mockReachTrend: ReachTrendDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date('2026-02-01')
  date.setDate(date.getDate() + i)
  const base = 500 + Math.sin(i / 3) * 200
  return {
    date: date.toISOString().split('T')[0],
    reach: Math.round(base + ((i * 137 + 43) % 300)),
    engagement: Math.round((base + ((i * 89 + 67) % 150)) * 0.06),
    clicks: Math.round(8 + ((i * 53 + 17) % 12)),
  }
})

// Campaign Metrics
export const mockCampaignMetrics: CampaignMetrics[] = [
  {
    campaignId: 'campaign-1',
    campaignName: "Mother's Day - Honor Her Story",
    brandName: 'Golden Horn Jewellery',
    reach: 4200,
    engagement: 312,
    ctr: 5.1,
    clicks: 214,
    score: 92,
  },
  {
    campaignId: 'campaign-2',
    campaignName: 'Spring Collection Launch',
    brandName: 'Golden Horn Jewellery',
    reach: 3800,
    engagement: 267,
    ctr: 4.3,
    clicks: 163,
    score: 85,
  },
  {
    campaignId: 'campaign-3',
    campaignName: 'Heritage Collection Awareness',
    brandName: 'Golden Horn Jewellery',
    reach: 2900,
    engagement: 189,
    ctr: 3.8,
    clicks: 110,
    score: 78,
  },
  {
    campaignId: 'campaign-4',
    campaignName: 'Summer Fitness Challenge',
    brandName: 'Urban Fitness Co',
    reach: 1500,
    engagement: 88,
    ctr: 2.1,
    clicks: 31,
    score: 58,
  },
]

// Creative Performance Metrics
export const mockCreativeMetrics: CreativeMetrics[] = [
  {
    creativeId: 'creative-1',
    creativeName: 'Honor Her Story - IG Story',
    campaignName: "Mother's Day",
    platform: 'Instagram',
    postUrl: 'https://instagram.com/p/abc123',
    publishedAt: new Date('2026-02-25'),
    thumbnailUrl: 'https://placehold.co/400x400/1c1b1b/e6d3c1?text=Story+1',
    reach: 4200,
    impressions: 5800,
    frequency: 1.38,
    likes: 287,
    comments: 23,
    shares: 12,
    saves: 45,
    engagementRate: 8.7,
    clicks: 214,
    ctr: 5.1,
    linkClicks: 189,
    videoViews: 3200,
    avgWatchTime: 8.5,
    completionRate: 72,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 92,
    performanceLabel: 'excellent',
    aiInsight: 'High engagement driven by emotional storytelling and strong CTA placement',
    aiSuggestion: 'Repurpose this creative for Facebook Stories to amplify reach',
  },
  {
    creativeId: 'creative-2',
    creativeName: 'Spring Necklace - Feed',
    campaignName: 'Spring Collection',
    platform: 'Instagram',
    postUrl: 'https://instagram.com/p/def456',
    publishedAt: new Date('2026-02-24'),
    thumbnailUrl: 'https://placehold.co/400x400/c5a55a/ffffff?text=Necklace',
    reach: 3100,
    impressions: 4200,
    frequency: 1.35,
    likes: 198,
    comments: 15,
    shares: 8,
    saves: 31,
    engagementRate: 8.1,
    clicks: 133,
    ctr: 4.3,
    linkClicks: 112,
    videoViews: null,
    avgWatchTime: null,
    completionRate: null,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 85,
    performanceLabel: 'excellent',
    aiInsight: 'Product photography drives high save rate, indicating purchase intent',
    aiSuggestion: 'Add carousel slides showing different angles and styling options',
  },
  {
    creativeId: 'creative-3',
    creativeName: 'Heritage Ring - Carousel',
    campaignName: 'Heritage Collection',
    platform: 'Facebook',
    postUrl: 'https://facebook.com/p/ghi789',
    publishedAt: new Date('2026-02-23'),
    thumbnailUrl: 'https://placehold.co/400x400/8b7355/ffffff?text=Ring',
    reach: 2900,
    impressions: 3800,
    frequency: 1.31,
    likes: 156,
    comments: 19,
    shares: 11,
    saves: 22,
    engagementRate: 7.2,
    clicks: 110,
    ctr: 3.8,
    linkClicks: 95,
    videoViews: null,
    avgWatchTime: null,
    completionRate: null,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 78,
    performanceLabel: 'good',
    aiInsight: 'Carousel format performs well but CTR could be higher',
    aiSuggestion: 'Add swipe-up CTA overlay on first slide to drive more clicks',
  },
  {
    creativeId: 'creative-4',
    creativeName: 'Workout Motivation - Reels',
    campaignName: 'Summer Fitness',
    platform: 'TikTok',
    postUrl: 'https://tiktok.com/@user/video/123',
    publishedAt: new Date('2026-02-22'),
    thumbnailUrl: 'https://placehold.co/400x400/00ff00/000000?text=Workout',
    reach: 1500,
    impressions: 2100,
    frequency: 1.4,
    likes: 67,
    comments: 8,
    shares: 3,
    saves: 6,
    engagementRate: 5.6,
    clicks: 44,
    ctr: 2.9,
    linkClicks: 31,
    videoViews: 1200,
    avgWatchTime: 4.2,
    completionRate: 38,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 65,
    performanceLabel: 'average',
    aiInsight: 'Low completion rate suggests hook needs improvement',
    aiSuggestion: 'Shorten intro to 1 second and add text overlay with benefit statement',
  },
  {
    creativeId: 'creative-5',
    creativeName: 'Ancient Craft - IG Story',
    campaignName: 'Heritage Collection',
    platform: 'Instagram',
    postUrl: 'https://instagram.com/p/jkl012',
    publishedAt: new Date('2026-02-21'),
    thumbnailUrl: 'https://placehold.co/400x400/e6d3c1/1c1b1b?text=Craft',
    reach: 980,
    impressions: 1400,
    frequency: 1.43,
    likes: 12,
    comments: 2,
    shares: 1,
    saves: 3,
    engagementRate: 1.8,
    clicks: 4,
    ctr: 0.3,
    linkClicks: 3,
    videoViews: 680,
    avgWatchTime: 2.1,
    completionRate: 15,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 28,
    performanceLabel: 'critical',
    aiInsight: 'Critical underperformance - extremely low CTR and engagement',
    aiSuggestion: 'Autopilot paused this creative. Replace with better hook and clearer CTA',
  },
  {
    creativeId: 'creative-6',
    creativeName: 'Earring Collection - Feed',
    campaignName: 'Spring Collection',
    platform: 'Instagram',
    postUrl: null,
    publishedAt: new Date('2026-02-26'),
    thumbnailUrl: 'https://placehold.co/400x400/f5f0ea/c5a55a?text=Earrings',
    reach: 2200,
    impressions: 2900,
    frequency: 1.32,
    likes: 142,
    comments: 11,
    shares: 7,
    saves: 18,
    engagementRate: 8.1,
    clicks: 89,
    ctr: 4.0,
    linkClicks: 76,
    videoViews: null,
    avgWatchTime: null,
    completionRate: null,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 82,
    performanceLabel: 'excellent',
    aiInsight: 'Solid performance across all metrics',
    aiSuggestion: 'Boost spend to maximize reach during peak hours',
  },
  {
    creativeId: 'creative-7',
    creativeName: 'Gift Guide - Carousel',
    campaignName: "Mother's Day",
    platform: 'Facebook',
    postUrl: 'https://facebook.com/p/mno345',
    publishedAt: new Date('2026-02-25'),
    thumbnailUrl: 'https://placehold.co/400x400/c5a55a/1c1b1b?text=Gift',
    reach: 1800,
    impressions: 2500,
    frequency: 1.39,
    likes: 98,
    comments: 14,
    shares: 9,
    saves: 27,
    engagementRate: 8.2,
    clicks: 72,
    ctr: 4.0,
    linkClicks: 63,
    videoViews: null,
    avgWatchTime: null,
    completionRate: null,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 79,
    performanceLabel: 'good',
    aiInsight: 'Carousel format drives high saves - users bookmarking for later',
    aiSuggestion: 'Create retargeting campaign for users who saved but didn\'t click',
  },
  {
    creativeId: 'creative-8',
    creativeName: 'Studio BTS - Reels',
    campaignName: 'Heritage Collection',
    platform: 'Instagram',
    postUrl: 'https://instagram.com/p/pqr678',
    publishedAt: new Date('2026-02-20'),
    thumbnailUrl: 'https://placehold.co/400x400/8b7355/e6d3c1?text=BTS',
    reach: 3400,
    impressions: 4700,
    frequency: 1.38,
    likes: 234,
    comments: 31,
    shares: 18,
    saves: 41,
    engagementRate: 9.5,
    clicks: 128,
    ctr: 3.8,
    linkClicks: 102,
    videoViews: 2800,
    avgWatchTime: 11.2,
    completionRate: 68,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 88,
    performanceLabel: 'excellent',
    aiInsight: 'Behind-the-scenes content drives high engagement and watch time',
    aiSuggestion: 'Create more BTS content showcasing craftsmanship',
  },
  {
    creativeId: 'creative-9',
    creativeName: 'Protein Shake Recipe - TikTok',
    campaignName: 'Summer Fitness',
    platform: 'TikTok',
    postUrl: 'https://tiktok.com/@user/video/456',
    publishedAt: new Date('2026-02-19'),
    thumbnailUrl: 'https://placehold.co/400x400/ff6b00/000000?text=Recipe',
    reach: 890,
    impressions: 1300,
    frequency: 1.46,
    likes: 45,
    comments: 6,
    shares: 4,
    saves: 12,
    engagementRate: 7.5,
    clicks: 27,
    ctr: 3.0,
    linkClicks: 21,
    videoViews: 720,
    avgWatchTime: 7.8,
    completionRate: 52,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 71,
    performanceLabel: 'good',
    aiInsight: 'Recipe content drives saves but lower reach than expected',
    aiSuggestion: 'Add trending audio and hashtags to boost discovery',
  },
  {
    creativeId: 'creative-10',
    creativeName: 'Transform Your Body - Story',
    campaignName: 'Summer Fitness',
    platform: 'Instagram',
    postUrl: 'https://instagram.com/p/stu901',
    publishedAt: new Date('2026-02-18'),
    thumbnailUrl: 'https://placehold.co/400x400/00ff00/ffffff?text=Transform',
    reach: 1200,
    impressions: 1700,
    frequency: 1.42,
    likes: 56,
    comments: 4,
    shares: 2,
    saves: 8,
    engagementRate: 5.8,
    clicks: 36,
    ctr: 3.0,
    linkClicks: 28,
    videoViews: 980,
    avgWatchTime: 5.4,
    completionRate: 44,
    spend: null,
    cpc: null,
    cpm: null,
    roas: null,
    performanceScore: 68,
    performanceLabel: 'average',
    aiInsight: 'Decent engagement but CTR could be higher',
    aiSuggestion: 'Test different CTA copy - "Swipe Up" vs "Learn More"',
  },
]

// AI Insights
export const mockAIInsights: AIInsight[] = [
  {
    id: 'insight-1',
    type: 'alert',
    title: 'Critical Underperformance Detected',
    description: '"Ancient Craft" Instagram Story has CTR of only 0.3%, significantly below campaign average of 4.2%.',
    affectedEntity: {
      type: 'creative',
      id: 'creative-5',
      name: 'Ancient Craft - IG Story',
    },
    suggestedAction: 'Autopilot has paused this creative. Generate a replacement with stronger hook and clearer CTA.',
    severity: 'critical',
    createdAt: new Date('2026-02-27T08:30:00'),
    isRead: false,
  },
  {
    id: 'insight-2',
    type: 'optimization',
    title: 'High Save Rate Opportunity',
    description: 'Spring Collection creatives have 32% higher save rate than average, indicating strong purchase intent.',
    affectedEntity: {
      type: 'campaign',
      id: 'campaign-2',
      name: 'Spring Collection Launch',
    },
    suggestedAction: 'Create retargeting campaign for users who saved but haven\'t clicked through yet.',
    severity: 'medium',
    createdAt: new Date('2026-02-26T14:20:00'),
    isRead: false,
  },
  {
    id: 'insight-3',
    type: 'trend',
    title: 'Instagram Reels Outperforming Stories',
    description: 'Reels content has 2.4x higher engagement rate and 68% completion rate vs 44% for Stories.',
    affectedEntity: null,
    suggestedAction: 'Shift budget allocation toward Reels format for next 7 days.',
    severity: 'medium',
    createdAt: new Date('2026-02-26T10:15:00'),
    isRead: true,
  },
  {
    id: 'insight-4',
    type: 'audience',
    title: 'Peak Engagement Time Identified',
    description: 'Posts published between 7-9 PM receive 43% higher engagement than morning posts.',
    affectedEntity: null,
    suggestedAction: 'Reschedule upcoming posts to align with 7-9 PM time window.',
    severity: 'low',
    createdAt: new Date('2026-02-25T16:45:00'),
    isRead: true,
  },
  {
    id: 'insight-5',
    type: 'optimization',
    title: 'Behind-the-Scenes Content Performing Well',
    description: 'BTS Reels have 88 performance score with 11.2s avg watch time, highest across all creatives.',
    affectedEntity: {
      type: 'creative',
      id: 'creative-8',
      name: 'Studio BTS - Reels',
    },
    suggestedAction: 'Produce more behind-the-scenes content showing craftsmanship process.',
    severity: 'low',
    createdAt: new Date('2026-02-24T12:00:00'),
    isRead: true,
  },
]

// Report Templates
export const mockReportTemplates: ReportTemplate[] = [
  {
    id: 'template-1',
    name: 'Weekly Summary',
    description: 'Quick overview of key metrics and top performers from the past 7 days',
    type: 'weekly',
    includesSections: ['KPIs', 'Top Creatives', 'Platform Breakdown', 'Alerts'],
  },
  {
    id: 'template-2',
    name: 'Monthly Overview',
    description: 'Comprehensive monthly report with trends, insights, and recommendations',
    type: 'monthly',
    includesSections: ['KPIs', 'Trends', 'All Campaigns', 'AI Insights', 'Recommendations'],
  },
  {
    id: 'template-3',
    name: 'Campaign Report',
    description: 'Deep dive into a specific campaign with creative-level analysis',
    type: 'campaign',
    includesSections: ['Campaign Stats', 'Creative Breakdown', 'A/B Comparison', 'Optimization Tips'],
  },
  {
    id: 'template-4',
    name: 'Custom Report',
    description: 'Build your own report by selecting date range, metrics, and sections',
    type: 'custom',
    includesSections: ['Custom KPIs', 'Custom Date Range', 'Custom Filters'],
  },
]

// Generated Reports (History)
export const mockGeneratedReports: GeneratedReport[] = [
  {
    id: 'report-1',
    templateId: 'template-1',
    templateName: 'Weekly Summary',
    dateRange: {
      start: new Date('2026-02-17'),
      end: new Date('2026-02-24'),
    },
    generatedAt: new Date('2026-02-24T09:00:00'),
    format: 'pdf',
    downloadUrl: '/reports/weekly-2026-02-24.pdf',
  },
  {
    id: 'report-2',
    templateId: 'template-2',
    templateName: 'Monthly Overview',
    dateRange: {
      start: new Date('2026-01-01'),
      end: new Date('2026-01-31'),
    },
    generatedAt: new Date('2026-02-01T08:00:00'),
    format: 'pdf',
    downloadUrl: '/reports/monthly-2026-01.pdf',
  },
  {
    id: 'report-3',
    templateId: 'template-3',
    templateName: 'Campaign Report',
    dateRange: {
      start: new Date('2026-02-20'),
      end: new Date('2026-02-27'),
    },
    generatedAt: new Date('2026-02-26T15:30:00'),
    format: 'csv',
    downloadUrl: '/reports/campaign-mothers-day.csv',
  },
]

// Scheduled Reports
export const mockScheduledReports: ScheduledReport[] = [
  {
    id: 'scheduled-1',
    templateId: 'template-1',
    templateName: 'Weekly Summary',
    frequency: 'weekly',
    nextRunAt: new Date('2026-03-03T09:00:00'),
    recipients: ['team@goldenhornjewellery.com'],
    isActive: true,
  },
  {
    id: 'scheduled-2',
    templateId: 'template-2',
    templateName: 'Monthly Overview',
    frequency: 'monthly',
    nextRunAt: new Date('2026-03-01T08:00:00'),
    recipients: ['director@goldenhornjewellery.com', 'analytics@agency.com'],
    isActive: true,
  },
]
