// Temporary icon placeholders until HugeIcons is properly configured
export const Add01Icon = ({ className }: { className?: string }) => <span className={className}>+</span>
export const Target03Icon = ({ className }: { className?: string }) => <span className={className}>🎯</span>
export const ArrowLeft01Icon = ({ className }: { className?: string }) => <span className={className}>←</span>
export const ArrowRight01Icon = ({ className }: { className?: string }) => <span className={className}>→</span>
export const Sparkles01Icon = ({ className }: { className?: string }) => <span className={className}>✨</span>
export const Image01Icon = ({ className }: { className?: string }) => <span className={className}>🖼️</span>
export const Edit02Icon = ({ className }: { className?: string }) => <span className={className}>✏️</span>
export const Download04Icon = ({ className }: { className?: string }) => <span className={className}>⬇️</span>
export const RefreshIcon = ({ className }: { className?: string }) => <span className={className}>🔄</span>
export const ClockIcon = ({ className }: { className?: string }) => <span className={className}>🕐</span>
export const Magic01Icon = ({ className }: { className?: string }) => <span className={className}>🪄</span>
export const Camera01Icon = ({ className }: { className?: string }) => <span className={className}>📷</span>
export const Calendar03Icon = ({ className }: { className?: string }) => <span className={className}>📅</span>
export const Analytics01Icon = ({ className }: { className?: string }) => <span className={className}>📊</span>
export const Lightning01Icon = ({ className }: { className?: string }) => <span className={className}>⚡</span>
export const Building03Icon = ({ className }: { className?: string }) => <span className={className}>🏢</span>
export const Menu01Icon = ({ className }: { className?: string }) => <span className={className}>☰</span>
export const Copy01Icon = ({ className }: { className?: string }) => <span className={className}>📋</span>
export const Delete02Icon = ({ className }: { className?: string }) => <span className={className}>🗑️</span>
export const CheckmarkCircle02Icon = ({ className }: { className?: string }) => <span className={className}>✅</span>
